;	extra_flags.ini - extra configurations for board
;	Copyright (C) 2025 Camren Chraplak
;
;	This program is free software: you can redistribute it and/or modify
;	it under the terms of the GNU General Public License as published by
;	the Free Software Foundation, either version 3 of the License, or
;	(at your option) any later version.
;
;	This program is distributed in the hope that it will be useful,
;	but WITHOUT ANY WARRANTY; without even the implied warranty of
;	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;	GNU General Public License for more details.
;
;	You should have received a copy of the GNU General Public License
;	along with this program.  If not, see <https://www.gnu.org/licenses/>.

[env]
build_flags =

	; previous flags

	; Custom Configuration Flags
	;-D DEFAULT_NVM=true ; Whether to use the default nvm methods over custom nvm methods

[env:board]
build_flags =
	${env.build_flags}

	; Debug Flags
	;-D __ERROR_DEBUG__ ; Debug for general error statements
	;-D __NVM_DEBUG__ ; Debug for data related to NVM